...

diff --git a/misc/termcolors/makexuse b/misc/termcolors/makexuse
--- a/misc/termcolors/makexuse
+++ b/misc/termcolors/makexuse
@@ -4,16 +4,20 @@
 [ -e "xuse" ] && rm xuse
 
 # copy target
-cat "$1" > xuse
+[ -e "${1}" ] && {
+    cat "$1" > xuse
+}
 
-# sed change stuff to add transparency
+# change stuff to add transparency
 sed -e "s/define /define a/g; s/ #/ #D9/g;" $1 >> xuse
 
 echo "#define xftfnt xft:Fira Mono:style=regular:size=9" >> xuse
 echo "#define fnt Fira Mono Regular 9" >> xuse
 
 # reload Xresources
-xrdb $HOME/.Xresources
+which xrdb && xrdb $HOME/.Xresources || {
+    echo "xrdb command not found, skipping..."
+}
 
 export barBG=$(xrdb -query | \
                grep "*background" | \
@@ -24,7 +28,9 @@ export barFG=$(xrdb -query | \
                awk '{print $NF}')
 
 # reset wall
-hsetroot -solid "${barBG}"
+which hsetroot && hsetroot -solid "${barBG}" || {
+    echo "hsetroot command not found, skippint..."
+}
 
 # chang bsp stuff
 pgrep bspwm && {
@@ -32,7 +38,6 @@ pgrep bspwm && {
   bspc config normal_border_color "${barBG}"
   bspc config focused_border_color "${barFG}"
   bspc config active_border_color "${barFG}"
-
   pgrep polybar && pkill polybar 2> /dev/null
   pgrep polybar || bargaps.sh 2> /dev/null
 
@@ -41,9 +46,7 @@ pgrep bspwm && {
 # update zathurarc
 ZRC=${HOME}/.config/zathura/zathurarc 
 
-[ -e ${ZRC} ] && {
-  rm ${ZRC}
-} 
+[ -e ${ZRC} ] && rm ${ZRC}
 
 echo "
 # Open document in fit-width mode by default
